version: "3.9"

services:
    php:
        build: .
        volumes: 
            - .:/var/www/html
        ports:
            - "1234:80"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}

    # database:
    #     image: mariadb:10.10
    #     volumes:
    #         - database:/var/lib/mysql
    #     environment:
    #         MYSQL_DATABASE: demo
    #         MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}

# volumes:
#     database: